dist: xenial
language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
  - "nightly"
install:
  - pip install -r api/requirements.txt
script:
  - python api/manage.py test
