version: '3'

services:
  db:
    image: postgres:11-alpine
  api:
    build: api/.
    command: python api/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  app:
    build:
      context: app/.
    volumes:
      - ./app:/code
    ports:
      - "4200:4200"
    command: npm start
